"""removed unique

Revision ID: 5df51e2e8925
Revises: 10faf4b216d0
Create Date: 2020-12-17 14:06:55.018917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df51e2e8925'
down_revision = '10faf4b216d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('donors_email_key', 'donors', type_='unique')
    op.drop_constraint('donors_name_key', 'donors', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('donors_name_key', 'donors', ['name'])
    op.create_unique_constraint('donors_email_key', 'donors', ['email'])
    # ### end Alembic commands ###
